# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6962c766d69c1059d6e9eabea68a37982354025e0cb8543dc35f740595edc66f6eeb1b3927fdbe7399a80273d6125a5ca8e868888e85c05b5b8728d2fc3ec0

test:
  secret_key_base: b7e5aa0ab5b3fd9d499bb60034b37f4a920237059a5b311bb9ac3b04fd096e4bad21f5c81b7f3bd108b8cca7956abb5778f1f9a097a85aaf6ccd8c5787c8cfb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
